# Configuration Hôtel 1
spring.application.name=hotelservice-h1
server.port=8081

# gRPC port
grpc.server.port=9091

# Infos hôtel (injectées dans DataInitializer)
hotel.code=H1
hotel.name=Hôtel Bellecour Lyon
hotel.stars=3
hotel.ville=Lyon
hotel.pays=France
hotel.rue=Place Bellecour
hotel.numero=15
hotel.latitude=45.7578
hotel.longitude=4.8320
hotel.image-url=https://example.com/room2.jpg

# H2 Database
spring.datasource.url=jdbc:h2:mem:hotel1db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false