spring.application.name=hotelservice
grpc.server.port=8081

# Hotel1 configuration
hotel.id=1
hotel.name=Grand Hotel Paris
hotel.stars=4
hotel.address.country=France
hotel.address.city=Paris
hotel.address.street=Avenue des Champs-Élysées
hotel.address.number=101
hotel.address.locality=8ème arrondissement
hotel.address.latitude=48.8698
hotel.address.longitude=2.3078