
spring.application.name=hotelservice-h1
server.port=8081

# gRPC port
grpc.server.port=9091


hotel.code=H1
hotel.name=Grand Hotel Paris
hotel.stars=4
hotel.ville=Paris
hotel.pays=France
hotel.rue=Avenue des Champs-Elysees
hotel.numero=101
hotel.latitude=48.8698
hotel.longitude=2.3078
hotel.image-url=http://localhost:8081/images/room.jpg

# H2 Database
spring.datasource.url=jdbc:h2:mem:hotel1db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false