spring.application.name=agenceservice
# Server port for REST API
server.port=8092

# Agency credentials configuration
agency.id=AGENCE2
agency.password=secret2
agency.name=VoyagePLUS

# Hotels configuration (liste dynamique)
# Format: hotels[index].name, hotels[index].address
hotels[0].name=Grand Hotel Paris
hotels[0].address=static://localhost:9091

hotels[1].name=Grand Hotel Occitanie
hotels[1].address=static://localhost:9092

# Logging
logging.level.com.example.agenceservice=DEBUG
logging.level.io.grpc=INFO